name = "vital-haven-project"
pages_build_output_dir = "./public"
compatibility_date = "2025-05-26"

[[d1_databases]]
binding = "DB"
database_name = "vitalhaven-db"
database_id = "a7ed3438-556c-4959-8672-a7cdb38a0f9f"